# Generated by Django 3.0.8 on 2020-09-11 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200911_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
