# Generated by Django 3.0.8 on 2020-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200911_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_publication',
            field=models.DateTimeField(default=None),
        ),
    ]
