# Generated by Django 3.0.8 on 2020-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20200911_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
